[program:aiev-horizon]
process_name=%(program_name)s
command=php /home/thanh/Documents/AIEV/apps/laravel-api/artisan horizon
autostart=true
autorestart=true
user=thanh
redirect_stderr=true
stdout_logfile=/home/thanh/Documents/AIEV/apps/laravel-api/storage/logs/horizon.log
stopwaitsecs=3600
